<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find rm_description)/urdf/common/omni_wheel.urdf.xacro"/>

    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="chassis_radius" value="0.196"/>
    <xacro:property name="wheel_offset_z" value="-0.04373"/>

    <xacro:macro name="chassis" params="roller_type">

        <link name="base_link">
            <inertial>
                <mass value="10.27"/>
                <origin xyz="-0.009309  0.003201  0.020754"/>
                <inertia ixx="2.165e-1" ixy="2.133e-5" ixz="6.137e-3" iyy="2.247e-1"
                         iyz="2.649e-3" izz="3.188e-1"/>
            </inertial>
            <visual>
                <origin xyz="0 0 -0.12" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/sentry/base.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.549 0.58 0.349"/>
                </geometry>
            </collision>
        </link>

        <xacro:omni_wheel prefix="left_front" connected_to="base_link"
                          wheel_x_offset="${chassis_radius/sqrt(2)}" wheel_y_offset="${chassis_radius/sqrt(2)}"
                          wheel_z_offset="${wheel_offset_z}" rotation_degree="${3*pi/4}" roller_type="${roller_type}"
                          max_effort="3.42" max_velocity="73"
        />
        <xacro:omni_wheel prefix="right_front" connected_to="base_link"
                          wheel_x_offset="${chassis_radius/sqrt(2)}" wheel_y_offset="${-chassis_radius/sqrt(2)}"
                          wheel_z_offset="${wheel_offset_z}" rotation_degree="${pi/4}" roller_type="${roller_type}"
                          max_effort="3.42" max_velocity="73"
        />
        <xacro:omni_wheel prefix="left_back" connected_to="base_link"
                          wheel_x_offset="${-chassis_radius/sqrt(2)}" wheel_y_offset="${chassis_radius/sqrt(2)}"
                          wheel_z_offset="${wheel_offset_z}" rotation_degree="${-3*pi/4}" roller_type="${roller_type}"
                          max_effort="3.42" max_velocity="73"
        />
        <xacro:omni_wheel prefix="right_back" connected_to="base_link"
                          wheel_x_offset="${-chassis_radius/sqrt(2)}" wheel_y_offset="${-chassis_radius/sqrt(2)}"
                          wheel_z_offset="${wheel_offset_z}" rotation_degree="${-pi/4}" roller_type="${roller_type}"
                          max_effort="3.42" max_velocity="73"
        />
        <xacro:wheel_transmission prefix="left_front" mechanical_reduction="13"/>
        <xacro:wheel_transmission prefix="right_front" mechanical_reduction="13"/>
        <xacro:wheel_transmission prefix="left_back" mechanical_reduction="13"/>
        <xacro:wheel_transmission prefix="right_back" mechanical_reduction="13"/>

    </xacro:macro>

</robot>
